version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: daphne -b 0.0.0.0 -p 8000 warehouse_manager.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
