# Generated by Django 5.2.1 on 2025-06-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_order_is_produced_order_produced_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("r", models.CharField(blank=True, max_length=10, null=True)),
                ("full_name", models.CharField(max_length=255)),
                (
                    "stock",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "available_quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("unit", models.CharField(max_length=10)),
                (
                    "purchase_price_net",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "sale_price_net",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("barcode", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "catalog_index",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "reserved",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("short_name", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "original_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "suppliers_will_deliver",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "recipients_will_receive",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "purchase_price_net_currency",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "vat_sale",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "margin_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("f", models.CharField(blank=True, max_length=10, null=True)),
                ("producer", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "article_number",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("s", models.CharField(blank=True, max_length=10, null=True)),
                ("attachment", models.CharField(blank=True, max_length=10, null=True)),
                ("marker", models.CharField(blank=True, max_length=10, null=True)),
                ("a", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "producer_index",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("cn_code", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "country_of_origin",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "jpk_classification",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "markup_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="order",
            name="color",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="diameter",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="shape",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="size",
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
