# Generated by Django 5.2.1 on 2025-06-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_component_alter_order_color_alter_order_diameter_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiffusorType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
    ]
