# Generated by Django 5.2.1 on 2025-06-09 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_diffusortype"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductToProduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_produced", models.BooleanField(default=False)),
                ("produced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.component",
                    ),
                ),
            ],
        ),
    ]
