# Generated by Django 5.2.1 on 2025-06-10 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_merchandise"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartsBuilder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_needed",
                    models.DecimalField(
                        decimal_places=3,
                        default=1,
                        help_text="Ilość materiału na 1 szt. produktu",
                        max_digits=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Dodatkowe uwagi")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "material",
                    models.ForeignKey(
                        help_text="Materiał użyty w produkcie",
                        limit_choices_to={"r": "Materiał"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_in_products",
                        to="inventory.component",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Produkt główny (SKU)",
                        limit_choices_to={"r": "Produkt"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts_recipes",
                        to="inventory.component",
                    ),
                ),
            ],
            options={
                "verbose_name": "Przepis produktu",
                "verbose_name_plural": "Przepisy produktów",
                "db_table": "parts_builder",
                "unique_together": {("product", "material")},
            },
        ),
    ]
