# Generated by Django 5.2.1 on 2025-06-10 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_partsbuilder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partsbuilder",
            name="material",
            field=models.ForeignKey(
                help_text="Materiał użyty w produkcie",
                limit_choices_to={"r__in": ["Materiał", "Towar"]},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="used_in_products",
                to="inventory.component",
            ),
        ),
    ]
