# Generated by Django 5.2.3 on 2025-06-12 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_alter_partsbuilder_material"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Merchandise",
        ),
        migrations.AlterField(
            model_name="partsbuilder",
            name="product",
            field=models.ForeignKey(
                help_text="Produkt główny (SKU)",
                limit_choices_to={"r__in": ["Towar"]},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parts_recipes",
                to="inventory.component",
            ),
        ),
    ]
