# Generated by Django 5.2.3 on 2025-06-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_delete_merchandise_alter_partsbuilder_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="color",
        ),
        migrations.RemoveField(
            model_name="product",
            name="shape",
        ),
        migrations.RemoveField(
            model_name="product",
            name="size",
        ),
        migrations.AddField(
            model_name="producttoproduction",
            name="uwagi",
            field=models.TextField(blank=True, null=True),
        ),
    ]
