# Generated by Django 5.2.3 on 2025-06-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_remove_product_color_remove_product_shape_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttoproduction",
            name="pilne",
            field=models.BooleanField(default=False),
        ),
    ]
