# Generated by Django 5.2.3 on 2025-06-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_producttoproduction_pilne"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttoproduction",
            name="komentarz",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
