# Generated by Django 5.2.3 on 2025-06-16 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_producttoproduction_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partsbuilder",
            name="product",
            field=models.ForeignKey(
                help_text="Produkt główny (SKU)",
                limit_choices_to={"r__in": ["Produkt", "Towar"]},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parts_recipes",
                to="inventory.component",
            ),
        ),
    ]
