# Generated by Django 5.2.3 on 2025-06-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0017_alter_partsbuilder_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttoproduction",
            name="missing_components_ordered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="producttoproduction",
            name="missing_parts_send_to_production",
            field=models.BooleanField(default=False),
        ),
    ]
