# Generated by Django 5.2.3 on 2025-06-26 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0018_producttoproduction_missing_components_ordered_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producttoproduction",
            name="missing_components_ordered",
        ),
    ]
