# Generated by Django 5.2.3 on 2025-06-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0019_remove_producttoproduction_missing_components_ordered"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttoproduction",
            name="missing_parts_ordered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
