# Generated by Django 5.2.3 on 2025-06-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0020_producttoproduction_missing_parts_ordered_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttoproduction",
            name="produced_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
