# Generated by Django 5.2.3 on 2025-07-02 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0021_producttoproduction_produced_quantity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="component",
            options={"verbose_name": "Komponent", "verbose_name_plural": "Komponenty"},
        ),
        migrations.AlterModelOptions(
            name="partsbuilder",
            options={
                "verbose_name": "Parts Builder",
                "verbose_name_plural": "Parts Builder",
            },
        ),
        migrations.AlterModelOptions(
            name="producttoproduction",
            options={"verbose_name": "Produkcja", "verbose_name_plural": "Produkcja"},
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
