# Generated by Django 5.2.3 on 2025-07-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0022_alter_component_options_alter_partsbuilder_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="chat_group",
            field=models.CharField(default="Ogólny", max_length=32),
        ),
    ]
