# Generated by Django 5.2.3 on 2025-07-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0023_chatmessage_chat_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="chat_group",
            field=models.CharField(default="General", max_length=32),
        ),
    ]
