# Generated by Django 5.2.3 on 2025-07-03 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0024_alter_chatmessage_chat_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                help_text="Odbiorca wiadomości prywatnej (None = wiadomość publiczna)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
