# Generated by Django 5.2.3 on 2025-07-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0026_chatmessageread"),
    ]

    operations = [
        migrations.AddField(
            model_name="partsbuilder",
            name="missing_parts_ordered",
            field=models.BooleanField(default=False),
        ),
    ]
