# Generated by Django 5.2.3 on 2025-07-09 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0027_partsbuilder_missing_parts_ordered"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventory",
            name="product",
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="supplier",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="Inventory",
        ),
        migrations.DeleteModel(
            name="Supplier",
        ),
    ]
