# Generated by Django 5.2.3 on 2025-07-09 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0028_remove_inventory_product_remove_inventory_supplier_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="DiffusorType",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
    ]
