# Generated by Django 5.2.3 on 2025-08-25 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0029_delete_diffusortype_delete_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partsbuilder",
            name="material",
            field=models.ForeignKey(
                help_text="Materiał użyty w produkcie",
                limit_choices_to={"r__in": ["Materiał", "Towar", "Produkt"]},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="used_in_products",
                to="inventory.component",
            ),
        ),
    ]
